# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.4

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -q Django=$DJANGO --use-mirrors
  - pip install -r requirements.txt
services:
  - mongodb

# command to run tests, e.g. python setup.py test
script: python setup.py test
